name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            qtbase5-dev \
            qt5-qmake \
            libqt5x11extras5-dev

      - name: Build
        run: |
          qmake
          make
          mkdir build
          mv myapp build/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
            install: mingw-w64-x86_64-toolchain
            msystem: mingw64
            release: false

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.11'
          host: 'windows'
          dir: '${{github.workspace}}/qt/'
          setup-python: false
      - name: Build
        run: |
          & "$env:QT_ROOT_DIR\bin\qmake"
          make
          mkdir build
          mv myapp.exe build/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

